"""
Integration Test Suite: Full Pipeline Positive Path Execution
=============================================================

Description:
    This test file serves as the definitive zero-mock integration test for the 
    Flow Analysis Engine pipeline. It exercises the entire software architecture 
    end-to-end through the main orchestration entry point (`src.main`).

Purpose:
    1. Validates that all core modules (parser, processor, spatial probe, zip 
       inspector, renderers, and main CLI) interoperate correctly together in 
       a live environment without relying on mocks or isolated stubs.
    2. Asserts the production of all expected physical output artifacts, including 
       the merged result JSON file and visual 3D verification PNG snapshots.
    3. Verifies the exact sequential progression of operational log messages 
       to guarantee architectural consistency and traceability.
"""

import json
import logging

from src.main import main


def test_full_pipeline_integration_positive_path(pipeline_test_environment, monkeypatch, caplog):
    """
    Executes the full pipeline integration positive path using the pre-configured environment fixture.
    """
    # We configure the logging capture level to INFO to monitor sequential operational milestones.
    caplog.set_level(logging.INFO)

    # We extract environment paths generated by the conftest fixture.
    env = pipeline_test_environment
    input_dir = env["input_dir"]
    input_file = env["input_file"]
    output_file = env["output_file"]

    # We configure the command-line arguments and patch sys.argv to simulate a real CLI invocation.
    cli_args = [
        "main.py",
        "--input_output_folder", str(input_dir),
        "--input_file_name", input_file.name,
        "--output_file_name", output_file.name
    ]
    monkeypatch.setattr("sys.argv", cli_args)

    # We execute the full pipeline orchestration via the main entry point.
    main()

    # We assert that all physical file artifacts and rendered 3D visual verification images have been successfully produced.
    assert output_file.exists(), "Merged output JSON file was not generated."
    assert (input_dir / "integration_voxel_verification.png").exists()
    assert (input_dir / "mesh_snapshot.png").exists()
    assert (input_dir / "step_snapshot.png").exists()
    assert (input_dir / "u_step_000005_3d_verification.png").exists()
    assert (input_dir / "p_step_000005_3d_verification.png").exists()

    # We verify the data contents and validation results written into the merged JSON output file.
    merged_data = json.loads(output_file.read_text())
    assert merged_data["results"]["status"] == "success"
    assert "spatial_interval_analysis" in merged_data["results"]
    assert "bernoulli_boundary_check" in merged_data["results"]
    assert merged_data["results"]["bernoulli_boundary_check"]["verified"] is True

    # We extract and inspect the log messages to ensure the exact sequential progression of pipeline milestones.
    log_messages = [record.message for record in caplog.records]
    
    expected_log_sequence = [
        "Initializing input parsing and schema validation module.",
        "Successfully parsed and validated input data.",
        "Initializing flow analysis processor and ZIP inspection module.",
        "Successfully executed flow processing and spatial probing.",
        "Initializing headless rendering and visualization pipeline.",
        "Voxel visualization rendered successfully.",
        "Initializing in-memory ZIP field renderer for archive.",
        "ZIP field rendering completed successfully.",
        "Writing merged output results to target destination.",
        "Successfully wrote final output file.",
        "Pipeline execution completed successfully."
    ]

    for log_item in expected_log_sequence:
        assert any(log_item in msg for msg in log_messages), f"Missing log step: {log_item}"
